### ISSUE TITLE
Community Feedback Request: Should We Move Over to `KeyboardEvent.code` and away from `KeyboardEvent.key`?

### ISSUE THREAD

**Issue by null-null-null** [null-null-null/ember-keyboard#34]
Currently, `ember-keyboard` uses [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) to determine which key was pressed. Despite its name, `key` doesn't return the actual key that was pressed, but rather the resolved value. For instance, it will return either 'a' or 'A', depending on whether or not shift is being held. Similarly, it'll return '1' for both the digit key at the top of the keyboard and the numpad.

On the other hand, we could [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code), which returns an unique code for every key on your keyboard, regardless of any modifier keys like shift. So it'll always return 'KeyA', with and without shift being held. It'll also return 'Numpad1' and 'Digit1', so there's the ability to distinguish between them if necessary. Support for it isn't great, but we could add a map that'll convert the deprecated `keyCode` into a `key` for the time being.

As I see it, the main benefits of sticking with `key` are:

1) Legibility. `keyDown('1')` vs `keyDown('Digit1')` and `keyDown('.')` vs `keyDown('Period')`.
2) Simplicity. `keyDown('1')` vs `keyDown('Digit1'), keyDown('Numpad1')`.
3) Reliability (?). I'm not sure how `code` will handle custom keyboard layouts. With `key` we at least know that if the user presses 'a', `key` will be 'a' regardless of what key it's bound to.

The benefits of `code` are:

1) Precision. If you need to, you can distinguish between 'Digit1' and 'Numpad1'.
2) Consistency. 'KeyA' will always be 'KeyA', regardless of capitalization. 'Digit1' will not sometimes be '1' and sometimes be '!'.

I'd like to hear everyone's thoughts about this, and then in about a month, I'll begin working on whichever route we choose.

**Comment by null-null-null** [comment]
With `key`, we can still distinguish between the equivalent of 'Digit1' and 'Numpad1' using [location](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/location). For instance, if we wanted to only respond to 'Numpad1', we might use an api like: `keyDown('1', { location: 3 })`.

So that just leaves 'Consistency' as a benefit of switching to `code`.

**Comment by bladnman** [comment]
I may not forward this issue much here but I thought I'd share. When building out the first series of keyboard handlers I attempted to set up hooks for `keyDown('=')` and `keyDown('shift+=')`. My myopic view of the world was to look at my keyboard and say "this key and the shift of the same key". It took me quite some time to figure out why it was not working and then rewire the second one as `keyDown('shift+\+')`. I'm certain I would have had the same troubles if I was trying to capture `a` and `shift+A`.

I like the ability to know if it's the keypad, etc. And your mention of using Location certainly solves that. The only thing is if I have a keyboard from Germany where the shifted value of a key is not the same as elsewhere how would I indicated that? 

I think I'd rather the keyboard `key` be the thing we indicate rather than the value. I'm not sure how support would field the call of how to do something for a non-US keyboard when they are just supposed to press `shift+4` (is that shift-pound, shift-euro, not sure).

**Comment by null-null-null** [comment]
`keyDown('shift++')` sounds like a bug in its own right. Thanks for bringing that to my attention.

My main concern with using `code` is the matter of consistency, especially when we take into account custom keyboard layouts. That being said, there are definitely use-cases for `code`. Perhaps it could be opt-in: `keyDown('KeyW', { isCode: true })`?

**Comment by null-null-null** [comment]
Actually, the opposite default is probably necessary: `keyDown('w', { isKey: true })`. This is because Safari (and a few mobile browsers) do not yet support `key`, and we can't accurately polyfill it. (While we can assume `shift` plus `a` will output `A`, we can't assume that `shift` plus `=` will output `+` for all keyboard layouts.) Because of this, I think we should make `code` the default after all.

**Comment by null-null-null** [comment]
There's a prerelease [here](https://github.com/null-null-null/ember-keyboard/releases/tag/v2.0.0-beta1) that move over to `code`. Try it out if you get a chance! I'll make this release official in a couple of weeks, unless we discover a reason not to.

**Comment by null-null-null** [comment]
Resolved by https://github.com/null-null-null/ember-keyboard/commit/50bab0cae9d4aa9fee63f930f511b0da6a9cfbe8.
